# Generated by Django 4.0.4 on 2022-05-12 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.CharField(max_length=800)),
                ('pais', models.CharField(max_length=35)),
                ('ocupacao', models.CharField(max_length=65)),
                ('telemovel', models.CharField(max_length=13)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=120)),
                ('nome_modelo', models.CharField(max_length=250)),
                ('tamanho', models.CharField(max_length=10)),
                ('referência', models.CharField(max_length=200)),
                ('preço', models.CharField(max_length=200)),
                ('data_lançamento', models.DateTimeField(verbose_name='data de lançamento')),
                ('tipo', models.CharField(default='Normal', max_length=64)),
                ('foto', models.CharField(max_length=800)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=350)),
                ('data', models.DateTimeField(verbose_name='data')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.modelo')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.utilizador')),
            ],
        ),
    ]
